sudo: required
services: 
  - docker
before_install: 
  - docker build -t tfadams/react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true tfadams/react-app npm run test
deploy:
  edge: true 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: react-app
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-967195537723"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: "$aws_devops_access_key"
  secret_access_key:
    secure: "$aws_devops_secret_key"
